module.exports = {
  arrowParens: 'avoid',
  bracketSameLine: false,
  bracketSpacing: true,
  endOfLine: 'lf',
  tabWidth: 2,
  trailingComma: 'all',
  printWidth: 120,
  proseWrap: 'always',
  semi: true,
  singleAttributePerLine: false,
  singleQuote: true,
  quoteProps: 'as-needed',
  useTabs: false,
  plugins: ['./node_modules/prettier-plugin-multiline-arrays'],
  multilineArraysWrapThreshold: 2,
};
